export const LOAD_VENDOR_TYPE_SUCCESS = 'LOAD_VENDOR_TYPE_SUCCESS';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const FILTER_BY_CATEGORY = 'FILTER_BY_CATEGORY ';
export const FILTER_BY_PRICE = 'FILTER_BY_PRICE ';
export const FILTER_BY_DISCOUNT = 'FILTER_BY_DISCOUNT ';
